apiVersion: v1
kind: Service
metadata:
    name: my-service 
spec:
    ports:
        targetPort: 8000
        port: 8001
        nodeport: 32000
    selector:
        app: my-deploy
    type: LoadBalancer
